### ISSUE TITLE
[Feature] Repair game and convert client (Star Rail)

### ISSUE THREAD

**Issue by prpjzz** [Scighost/Starward#354]
### Description

Currently, Star Rail's Convert Launcher feature cannot be implemented, because the original Launcher does not support data verification.

However, in the in-game, at the beginning of the game, there is a part that can be seen as "data verification," does this feature require the Dispatcher key of both versions for fast conversion? And how can Dispatcher Key get it? I have MiHoYo (Chinese version) and HoYoVerse (International) accounts. I looked online and there were no documents related to this.

Hope you help me. Thank you ~

### Starward Version

0.9.1

### Windows Version

19044.3324

**Comment by Scighost** [comment]
Thanks for your suggestion. But I won't implement repairing game and converting server for Star Rail. Because:

- Dispatcher Key changes with each version of Star Rail, I must update it every 6 weeks. It's a heavy burden.
- The different files of China and Global client of Star Rail are in root folder. But in-game data verification doesn't contain these files. So there's no way to convert client except to download full package.

**Comment by prpjzz** [comment]
So unless Mihoyo's official Launcher supports verification data, this feature can't be added, right?

**Comment by Scighost** [comment]
> So unless Mihoyo's official Launcher supports verification data, this feature can't be added, right?

Yeah

**Comment by prpjzz** [comment]
Hello, Repair Data Feature has appear in new version of HSR Launcher, you can implement convert launcher from CN to OS and vice versa.
![image](https://github.com/Scighost/Starward/assets/89702898/08f58676-bdf9-4d46-b666-c6006e217eb4)

**Comment by Scighost** [comment]
Thank you for your continuous attention. I will add this feature latter.

**Comment by Scighost** [comment]
Sorry, I cannot implement it. Because `$data.game.latest.decompressed_path` of global launcher api is null. There's no way to get the latest `pkg_version` except downloading complete package, which is unacceptable.

[CN launcher api](https://api-launcher-static.mihoyo.com/hkrpg_cn/mdk/launcher/api/resource?channel_id=1&key=6KcVuOkbcqjJomjZ&launcher_id=33&sub_channel_id=1)
[OS launcher api](https://hkrpg-launcher-static.hoyoverse.com/hkrpg_global/mdk/launcher/api/resource?channel_id=1&key=vplOVX8Vn7cwG8yb&launcher_id=35&sub_channel_id=1)

**Comment by prpjzz** [comment]
Oh my god... I see it. If get pkg_version on global version, you must download full package. This is unacceptable. 

We'll never have enough time to download full game just to get one pkg_version file.

**Comment by Scighost** [comment]
There is another way. According to CN api, we knew all separate files are in subfolder `unzip`, and the prefix of `$data.game.latest.path` and `$data.game.latest.decompressed_path` are the same. So we can easily get `decompressed_path` from `path`.

**Comment by Scighost** [comment]
Feature implemented at 0.10.2
