### ISSUE TITLE
[Feature/Concept] New Installer UI

### ISSUE THREAD

**Issue by studiobuttermedia** [Scighost/Starward#448]
### Summary

I made a redesign Installer UI using In-Game Loading Screen Texts, Launcher's Assets and Windows Assets and Background Music 

### Solution or Design

I had an idea where I can make something similar to Honkai Impact 3rd Installation screen, the installer use Starward Background Assets transition from one image to the next with music playing in the background. 
(Music should use Copyright-free for distribution, the music shown here is an example)

During Download, depending on the game you install, you will see some game tips. Those tips can be seen in the game loading screen (i.e: Genshin when going from one region to another). These tips are taken from the Wiki Online. When the download is complete, the tips are hidden to save memory to start verifying the files and unzip.

Some Elements were made by hand using Krita like the Arrow for the Start Game button, the checkbox. The Volume Icon looks like the Windows 10 Volume Icon. The Spinning Circle was recorded from a Virtual Machine when booting Windows 11 (The original Spinning Circle by Microsoft is coded using XAML Animation)

Some stuff that I forgot to add in before posting this concept:
- After Install, user will show a message saying, "There might be additional files need to download when running the game, Launch the game to complete the install and start playing." same time the Start Game button appears.
- I forgot the part where the game unzip. Tho this can be seen as doing Pre-install files
- The Close and Minimize button is missing. 
- I was thinking that for each game background should show a different tip for that game. But I don't have time, so I use Genshin Loading Screen Tip. Tho it would be awesome if it did that. 

Concept Video: https://youtu.be/Ye9B6Dxk_mg
(This took me 3 days + little neck pain for a 3-minute video. It was made on CapCut tho I assume coding this will be longer than what I have done)

**Comment by Scighost** [comment]
Hello, thanks for your interest in Starward. Your suggestion is really amazing and has a high degree of completion.

As you said, the design is similar to Honkai Impact 3rd's installation, which is shown in game update. During the downloading and loading of game, developers need to keep the player's attention as much as possible to make the process seem as slow as possible. So gorgeous animations, beautiful background music, and even PV are good choices. What's more, this period of time is not very long, because most resources are downloaded before the game starting (except Honkai Impact 3rd).

The download process in the game launcher may take a long time, ranging from a dozen minutes to a few hours. In order not to affect the user's normal computer experience, the launcher needs to minimize the occupation of non-network resources. Your design is undoubtedly very attractive, but I think the present scheme is superior in terms of practicality.

Finally, thank you again for your advice and support of Starward.
